#!/bin/bash
# Copyright IBM Corporation. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

SCRIPT_DIR="$(dirname "${0}")"
SCRIPT_NAME="$(basename "${0}")"

source "${SCRIPT_DIR}/utilities/version.sh"
source "${SCRIPT_DIR}/utilities/utilities.sh"
source "${SCRIPT_DIR}/utilities/cmdline.sh"

run() {
  startRun
  setDefaultFlags
  OPTIONS[resources-nodes-allnamespaces]=true
  OPTIONS[resources-pods-allnamespaces]=true
  OPTIONS[resources-events-allnamespaces]=true
  OPTIONS[resources-securitycontextconstraints-allnamespaces]=true
  OPTIONS[logs-crashloopbackoff]=true
  processCommandLine "${@}"
  defaultProcessing
  endRun
}

run "${@}" 2>&1 | tee -a "${TEE_FILE}"
